name: IceCat
version: '${version}'
main: jp.iceserver.icecat.IceCat
api-version: 1.18
authors: [ Minidon ]
description: アイス生活鯖のインフラ周りを補うためのプラグイン
website: https://github.com/IceServerLab/IceCat

commands:
  c2c:
    description: 個人間取引の画面を開くコマンド
  coi:
    description: /co i を省略したコマンド